// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/item/item.proto

package item

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ItemPrimaryKey struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemPrimaryKey) Reset()         { *m = ItemPrimaryKey{} }
func (m *ItemPrimaryKey) String() string { return proto.CompactTextString(m) }
func (*ItemPrimaryKey) ProtoMessage()    {}
func (*ItemPrimaryKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_82cd2361cd518f46, []int{0}
}

func (m *ItemPrimaryKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemPrimaryKey.Unmarshal(m, b)
}
func (m *ItemPrimaryKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemPrimaryKey.Marshal(b, m, deterministic)
}
func (m *ItemPrimaryKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemPrimaryKey.Merge(m, src)
}
func (m *ItemPrimaryKey) XXX_Size() int {
	return xxx_messageInfo_ItemPrimaryKey.Size(m)
}
func (m *ItemPrimaryKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemPrimaryKey.DiscardUnknown(m)
}

var xxx_messageInfo_ItemPrimaryKey proto.InternalMessageInfo

func (m *ItemPrimaryKey) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Item struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Info                 string   `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Price                int64    `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_82cd2361cd518f46, []int{1}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *Item) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type CreateItem struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Price                int64    `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateItem) Reset()         { *m = CreateItem{} }
func (m *CreateItem) String() string { return proto.CompactTextString(m) }
func (*CreateItem) ProtoMessage()    {}
func (*CreateItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_82cd2361cd518f46, []int{2}
}

func (m *CreateItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateItem.Unmarshal(m, b)
}
func (m *CreateItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateItem.Marshal(b, m, deterministic)
}
func (m *CreateItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateItem.Merge(m, src)
}
func (m *CreateItem) XXX_Size() int {
	return xxx_messageInfo_CreateItem.Size(m)
}
func (m *CreateItem) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateItem.DiscardUnknown(m)
}

var xxx_messageInfo_CreateItem proto.InternalMessageInfo

func (m *CreateItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateItem) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *CreateItem) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type UpdateItem struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Info                 string   `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Price                int64    `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateItem) Reset()         { *m = UpdateItem{} }
func (m *UpdateItem) String() string { return proto.CompactTextString(m) }
func (*UpdateItem) ProtoMessage()    {}
func (*UpdateItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_82cd2361cd518f46, []int{3}
}

func (m *UpdateItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItem.Unmarshal(m, b)
}
func (m *UpdateItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItem.Marshal(b, m, deterministic)
}
func (m *UpdateItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItem.Merge(m, src)
}
func (m *UpdateItem) XXX_Size() int {
	return xxx_messageInfo_UpdateItem.Size(m)
}
func (m *UpdateItem) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItem.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItem proto.InternalMessageInfo

func (m *UpdateItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateItem) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *UpdateItem) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type GetListItemRequest struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Order                string   `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListItemRequest) Reset()         { *m = GetListItemRequest{} }
func (m *GetListItemRequest) String() string { return proto.CompactTextString(m) }
func (*GetListItemRequest) ProtoMessage()    {}
func (*GetListItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82cd2361cd518f46, []int{4}
}

func (m *GetListItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListItemRequest.Unmarshal(m, b)
}
func (m *GetListItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListItemRequest.Marshal(b, m, deterministic)
}
func (m *GetListItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListItemRequest.Merge(m, src)
}
func (m *GetListItemRequest) XXX_Size() int {
	return xxx_messageInfo_GetListItemRequest.Size(m)
}
func (m *GetListItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListItemRequest proto.InternalMessageInfo

func (m *GetListItemRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetListItemRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetListItemRequest) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

type GetListItemResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Items                []*Item  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListItemResponse) Reset()         { *m = GetListItemResponse{} }
func (m *GetListItemResponse) String() string { return proto.CompactTextString(m) }
func (*GetListItemResponse) ProtoMessage()    {}
func (*GetListItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82cd2361cd518f46, []int{5}
}

func (m *GetListItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListItemResponse.Unmarshal(m, b)
}
func (m *GetListItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListItemResponse.Marshal(b, m, deterministic)
}
func (m *GetListItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListItemResponse.Merge(m, src)
}
func (m *GetListItemResponse) XXX_Size() int {
	return xxx_messageInfo_GetListItemResponse.Size(m)
}
func (m *GetListItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListItemResponse proto.InternalMessageInfo

func (m *GetListItemResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetListItemResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type MessageString struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageString) Reset()         { *m = MessageString{} }
func (m *MessageString) String() string { return proto.CompactTextString(m) }
func (*MessageString) ProtoMessage()    {}
func (*MessageString) Descriptor() ([]byte, []int) {
	return fileDescriptor_82cd2361cd518f46, []int{6}
}

func (m *MessageString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageString.Unmarshal(m, b)
}
func (m *MessageString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageString.Marshal(b, m, deterministic)
}
func (m *MessageString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageString.Merge(m, src)
}
func (m *MessageString) XXX_Size() int {
	return xxx_messageInfo_MessageString.Size(m)
}
func (m *MessageString) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageString.DiscardUnknown(m)
}

var xxx_messageInfo_MessageString proto.InternalMessageInfo

func (m *MessageString) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ItemPrimaryKey)(nil), "item.ItemPrimaryKey")
	proto.RegisterType((*Item)(nil), "item.Item")
	proto.RegisterType((*CreateItem)(nil), "item.CreateItem")
	proto.RegisterType((*UpdateItem)(nil), "item.UpdateItem")
	proto.RegisterType((*GetListItemRequest)(nil), "item.GetListItemRequest")
	proto.RegisterType((*GetListItemResponse)(nil), "item.GetListItemResponse")
	proto.RegisterType((*MessageString)(nil), "item.MessageString")
}

func init() {
	proto.RegisterFile("protos/item/item.proto", fileDescriptor_82cd2361cd518f46)
}

var fileDescriptor_82cd2361cd518f46 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x5d, 0x6b, 0xea, 0x40,
	0x10, 0x35, 0x1f, 0x46, 0xee, 0x88, 0xde, 0xcb, 0x2a, 0x92, 0xeb, 0x53, 0xd8, 0xa7, 0xdc, 0x87,
	0x6b, 0xc1, 0xd2, 0xf7, 0x62, 0x05, 0xb1, 0xad, 0x50, 0x62, 0x0b, 0xc5, 0xb7, 0xd4, 0x8c, 0xb2,
	0x60, 0x3e, 0xba, 0xbb, 0x16, 0xfc, 0x09, 0xfd, 0xd7, 0x65, 0x77, 0x4d, 0xa3, 0xd6, 0xbe, 0xf5,
	0x25, 0xcc, 0x9c, 0x39, 0x7b, 0x66, 0x32, 0x67, 0x17, 0x7a, 0x05, 0xcf, 0x65, 0x2e, 0x2e, 0x98,
	0xc4, 0x54, 0x7f, 0x06, 0x1a, 0x20, 0xae, 0x8a, 0x69, 0x00, 0xed, 0xa9, 0xc4, 0xf4, 0x81, 0xb3,
	0x34, 0xe6, 0xbb, 0x3b, 0xdc, 0x91, 0x36, 0xd8, 0x2c, 0xf1, 0xad, 0xc0, 0x0a, 0xeb, 0x91, 0xcd,
	0x12, 0xfa, 0x08, 0xae, 0x62, 0x9c, 0xe2, 0x84, 0x80, 0x9b, 0xc5, 0x29, 0xfa, 0x76, 0x60, 0x85,
	0xbf, 0x22, 0x1d, 0x2b, 0x8c, 0x65, 0xab, 0xdc, 0x77, 0x0c, 0xa6, 0x62, 0xd2, 0x85, 0x7a, 0xc1,
	0xd9, 0x12, 0x7d, 0x37, 0xb0, 0x42, 0x27, 0x32, 0x09, 0xbd, 0x05, 0xb8, 0xe1, 0x18, 0x4b, 0xd4,
	0xda, 0xa5, 0x96, 0x75, 0x46, 0xcb, 0x3e, 0xa7, 0xe5, 0x1c, 0x6a, 0x2d, 0x00, 0x9e, 0x8a, 0xa4,
	0xd4, 0xfa, 0xd9, 0x39, 0x9f, 0x81, 0x4c, 0x50, 0xde, 0x33, 0x21, 0x95, 0x78, 0x84, 0xaf, 0x5b,
	0x14, 0x52, 0x71, 0x37, 0x2c, 0x65, 0x52, 0xb7, 0x71, 0x22, 0x93, 0x90, 0x1e, 0x78, 0xf9, 0x6a,
	0x25, 0x50, 0xea, 0x5e, 0x4e, 0xb4, 0xcf, 0x14, 0x3b, 0xe7, 0x09, 0xf2, 0x7d, 0x3b, 0x93, 0xd0,
	0x19, 0x74, 0x8e, 0x94, 0x45, 0x91, 0x67, 0x02, 0x15, 0x79, 0x99, 0x6f, 0xb3, 0x4f, 0x69, 0x9d,
	0x90, 0x00, 0xea, 0xca, 0x2e, 0xe1, 0xdb, 0x81, 0x13, 0x36, 0x87, 0x30, 0xd0, 0x46, 0xea, 0x83,
	0xa6, 0x40, 0xff, 0x41, 0x6b, 0x86, 0x42, 0xc4, 0x6b, 0x9c, 0x4b, 0xce, 0xb2, 0x35, 0xf1, 0xa1,
	0x91, 0x1a, 0x60, 0xbf, 0xd6, 0x32, 0x1d, 0xbe, 0xdb, 0xd0, 0x54, 0x47, 0xe7, 0xc8, 0xdf, 0xd8,
	0x12, 0x49, 0x08, 0x9e, 0xf1, 0x82, 0xfc, 0x31, 0xba, 0x95, 0x33, 0xfd, 0x83, 0x4e, 0xb4, 0x46,
	0xfe, 0x43, 0x63, 0x82, 0x72, 0xb4, 0x9b, 0x8e, 0x49, 0xb7, 0x2a, 0x54, 0x97, 0xe7, 0x84, 0x7e,
	0xad, 0xe9, 0xea, 0x17, 0x89, 0x6f, 0x0a, 0x5f, 0x77, 0xd9, 0xff, 0x7b, 0xa6, 0x62, 0x76, 0x41,
	0x6b, 0x6a, 0x34, 0x63, 0x6d, 0x39, 0x5a, 0x65, 0xf4, 0x49, 0xaf, 0x2b, 0xf0, 0xc6, 0xb8, 0x41,
	0x89, 0xdf, 0x4c, 0xd6, 0x31, 0xe8, 0xd1, 0x8e, 0x68, 0x6d, 0xf4, 0x7b, 0xd1, 0x5a, 0x63, 0xa6,
	0x5f, 0x84, 0x7e, 0x1c, 0x2f, 0x9e, 0x8e, 0x2f, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x82, 0xeb,
	0x18, 0x69, 0x37, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ItemServiceClient is the client API for ItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ItemServiceClient interface {
	Create(ctx context.Context, in *CreateItem, opts ...grpc.CallOption) (*Item, error)
	GetByID(ctx context.Context, in *ItemPrimaryKey, opts ...grpc.CallOption) (*Item, error)
	GetList(ctx context.Context, in *GetListItemRequest, opts ...grpc.CallOption) (*GetListItemResponse, error)
	Update(ctx context.Context, in *UpdateItem, opts ...grpc.CallOption) (*Item, error)
	Delete(ctx context.Context, in *ItemPrimaryKey, opts ...grpc.CallOption) (*MessageString, error)
}

type itemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewItemServiceClient(cc grpc.ClientConnInterface) ItemServiceClient {
	return &itemServiceClient{cc}
}

func (c *itemServiceClient) Create(ctx context.Context, in *CreateItem, opts ...grpc.CallOption) (*Item, error) {
	out := new(Item)
	err := c.cc.Invoke(ctx, "/item.ItemService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) GetByID(ctx context.Context, in *ItemPrimaryKey, opts ...grpc.CallOption) (*Item, error) {
	out := new(Item)
	err := c.cc.Invoke(ctx, "/item.ItemService/GetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) GetList(ctx context.Context, in *GetListItemRequest, opts ...grpc.CallOption) (*GetListItemResponse, error) {
	out := new(GetListItemResponse)
	err := c.cc.Invoke(ctx, "/item.ItemService/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) Update(ctx context.Context, in *UpdateItem, opts ...grpc.CallOption) (*Item, error) {
	out := new(Item)
	err := c.cc.Invoke(ctx, "/item.ItemService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) Delete(ctx context.Context, in *ItemPrimaryKey, opts ...grpc.CallOption) (*MessageString, error) {
	out := new(MessageString)
	err := c.cc.Invoke(ctx, "/item.ItemService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemServiceServer is the server API for ItemService service.
type ItemServiceServer interface {
	Create(context.Context, *CreateItem) (*Item, error)
	GetByID(context.Context, *ItemPrimaryKey) (*Item, error)
	GetList(context.Context, *GetListItemRequest) (*GetListItemResponse, error)
	Update(context.Context, *UpdateItem) (*Item, error)
	Delete(context.Context, *ItemPrimaryKey) (*MessageString, error)
}

// UnimplementedItemServiceServer can be embedded to have forward compatible implementations.
type UnimplementedItemServiceServer struct {
}

func (*UnimplementedItemServiceServer) Create(ctx context.Context, req *CreateItem) (*Item, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedItemServiceServer) GetByID(ctx context.Context, req *ItemPrimaryKey) (*Item, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (*UnimplementedItemServiceServer) GetList(ctx context.Context, req *GetListItemRequest) (*GetListItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (*UnimplementedItemServiceServer) Update(ctx context.Context, req *UpdateItem) (*Item, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedItemServiceServer) Delete(ctx context.Context, req *ItemPrimaryKey) (*MessageString, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterItemServiceServer(s *grpc.Server, srv ItemServiceServer) {
	s.RegisterService(&_ItemService_serviceDesc, srv)
}

func _ItemService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.ItemService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).Create(ctx, req.(*CreateItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.ItemService/GetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).GetByID(ctx, req.(*ItemPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.ItemService/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).GetList(ctx, req.(*GetListItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.ItemService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).Update(ctx, req.(*UpdateItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.ItemService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).Delete(ctx, req.(*ItemPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

var _ItemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "item.ItemService",
	HandlerType: (*ItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ItemService_Create_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _ItemService_GetByID_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _ItemService_GetList_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ItemService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ItemService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/item/item.proto",
}
