// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/auth/auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserPrimaryKey struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPrimaryKey) Reset()         { *m = UserPrimaryKey{} }
func (m *UserPrimaryKey) String() string { return proto.CompactTextString(m) }
func (*UserPrimaryKey) ProtoMessage()    {}
func (*UserPrimaryKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e5b8102c891c02, []int{0}
}

func (m *UserPrimaryKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPrimaryKey.Unmarshal(m, b)
}
func (m *UserPrimaryKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPrimaryKey.Marshal(b, m, deterministic)
}
func (m *UserPrimaryKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPrimaryKey.Merge(m, src)
}
func (m *UserPrimaryKey) XXX_Size() int {
	return xxx_messageInfo_UserPrimaryKey.Size(m)
}
func (m *UserPrimaryKey) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPrimaryKey.DiscardUnknown(m)
}

var xxx_messageInfo_UserPrimaryKey proto.InternalMessageInfo

func (m *UserPrimaryKey) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role                 string   `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e5b8102c891c02, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type CreateUser struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	GenerateToken        bool     `protobuf:"varint,5,opt,name=generateToken,proto3" json:"generateToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUser) Reset()         { *m = CreateUser{} }
func (m *CreateUser) String() string { return proto.CompactTextString(m) }
func (*CreateUser) ProtoMessage()    {}
func (*CreateUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e5b8102c891c02, []int{2}
}

func (m *CreateUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUser.Unmarshal(m, b)
}
func (m *CreateUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUser.Marshal(b, m, deterministic)
}
func (m *CreateUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUser.Merge(m, src)
}
func (m *CreateUser) XXX_Size() int {
	return xxx_messageInfo_CreateUser.Size(m)
}
func (m *CreateUser) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUser.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUser proto.InternalMessageInfo

func (m *CreateUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUser) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *CreateUser) GetGenerateToken() bool {
	if m != nil {
		return m.GenerateToken
	}
	return false
}

type UserLoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginRequest) Reset()         { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()    {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e5b8102c891c02, []int{3}
}

func (m *UserLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginRequest.Unmarshal(m, b)
}
func (m *UserLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginRequest.Marshal(b, m, deterministic)
}
func (m *UserLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginRequest.Merge(m, src)
}
func (m *UserLoginRequest) XXX_Size() int {
	return xxx_messageInfo_UserLoginRequest.Size(m)
}
func (m *UserLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginRequest proto.InternalMessageInfo

func (m *UserLoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserLoginResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginResponse) Reset()         { *m = UserLoginResponse{} }
func (m *UserLoginResponse) String() string { return proto.CompactTextString(m) }
func (*UserLoginResponse) ProtoMessage()    {}
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e5b8102c891c02, []int{4}
}

func (m *UserLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginResponse.Unmarshal(m, b)
}
func (m *UserLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginResponse.Marshal(b, m, deterministic)
}
func (m *UserLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginResponse.Merge(m, src)
}
func (m *UserLoginResponse) XXX_Size() int {
	return xxx_messageInfo_UserLoginResponse.Size(m)
}
func (m *UserLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginResponse proto.InternalMessageInfo

func (m *UserLoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserLoginResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *UserLoginResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type GetListUserRequest struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Order                string   `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListUserRequest) Reset()         { *m = GetListUserRequest{} }
func (m *GetListUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetListUserRequest) ProtoMessage()    {}
func (*GetListUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e5b8102c891c02, []int{5}
}

func (m *GetListUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListUserRequest.Unmarshal(m, b)
}
func (m *GetListUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListUserRequest.Marshal(b, m, deterministic)
}
func (m *GetListUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListUserRequest.Merge(m, src)
}
func (m *GetListUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetListUserRequest.Size(m)
}
func (m *GetListUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListUserRequest proto.InternalMessageInfo

func (m *GetListUserRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetListUserRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetListUserRequest) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

type GetListUserResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListUserResponse) Reset()         { *m = GetListUserResponse{} }
func (m *GetListUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetListUserResponse) ProtoMessage()    {}
func (*GetListUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e5b8102c891c02, []int{6}
}

func (m *GetListUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListUserResponse.Unmarshal(m, b)
}
func (m *GetListUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListUserResponse.Marshal(b, m, deterministic)
}
func (m *GetListUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListUserResponse.Merge(m, src)
}
func (m *GetListUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetListUserResponse.Size(m)
}
func (m *GetListUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListUserResponse proto.InternalMessageInfo

func (m *GetListUserResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetListUserResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UpdateUser struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role                 string   `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUser) Reset()         { *m = UpdateUser{} }
func (m *UpdateUser) String() string { return proto.CompactTextString(m) }
func (*UpdateUser) ProtoMessage()    {}
func (*UpdateUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e5b8102c891c02, []int{7}
}

func (m *UpdateUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUser.Unmarshal(m, b)
}
func (m *UpdateUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUser.Marshal(b, m, deterministic)
}
func (m *UpdateUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUser.Merge(m, src)
}
func (m *UpdateUser) XXX_Size() int {
	return xxx_messageInfo_UpdateUser.Size(m)
}
func (m *UpdateUser) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUser.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUser proto.InternalMessageInfo

func (m *UpdateUser) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUser) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *UpdateUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CheckUriRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Uri                  string   `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUriRequest) Reset()         { *m = CheckUriRequest{} }
func (m *CheckUriRequest) String() string { return proto.CompactTextString(m) }
func (*CheckUriRequest) ProtoMessage()    {}
func (*CheckUriRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e5b8102c891c02, []int{8}
}

func (m *CheckUriRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUriRequest.Unmarshal(m, b)
}
func (m *CheckUriRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUriRequest.Marshal(b, m, deterministic)
}
func (m *CheckUriRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUriRequest.Merge(m, src)
}
func (m *CheckUriRequest) XXX_Size() int {
	return xxx_messageInfo_CheckUriRequest.Size(m)
}
func (m *CheckUriRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUriRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUriRequest proto.InternalMessageInfo

func (m *CheckUriRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CheckUriRequest) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *CheckUriRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type CheckUriResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUriResponse) Reset()         { *m = CheckUriResponse{} }
func (m *CheckUriResponse) String() string { return proto.CompactTextString(m) }
func (*CheckUriResponse) ProtoMessage()    {}
func (*CheckUriResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e5b8102c891c02, []int{9}
}

func (m *CheckUriResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUriResponse.Unmarshal(m, b)
}
func (m *CheckUriResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUriResponse.Marshal(b, m, deterministic)
}
func (m *CheckUriResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUriResponse.Merge(m, src)
}
func (m *CheckUriResponse) XXX_Size() int {
	return xxx_messageInfo_CheckUriResponse.Size(m)
}
func (m *CheckUriResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUriResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUriResponse proto.InternalMessageInfo

func (m *CheckUriResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *CheckUriResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CheckUriResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MessageString struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageString) Reset()         { *m = MessageString{} }
func (m *MessageString) String() string { return proto.CompactTextString(m) }
func (*MessageString) ProtoMessage()    {}
func (*MessageString) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6e5b8102c891c02, []int{10}
}

func (m *MessageString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageString.Unmarshal(m, b)
}
func (m *MessageString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageString.Marshal(b, m, deterministic)
}
func (m *MessageString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageString.Merge(m, src)
}
func (m *MessageString) XXX_Size() int {
	return xxx_messageInfo_MessageString.Size(m)
}
func (m *MessageString) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageString.DiscardUnknown(m)
}

var xxx_messageInfo_MessageString proto.InternalMessageInfo

func (m *MessageString) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*UserPrimaryKey)(nil), "user_service.UserPrimaryKey")
	proto.RegisterType((*User)(nil), "user_service.User")
	proto.RegisterType((*CreateUser)(nil), "user_service.CreateUser")
	proto.RegisterType((*UserLoginRequest)(nil), "user_service.UserLoginRequest")
	proto.RegisterType((*UserLoginResponse)(nil), "user_service.UserLoginResponse")
	proto.RegisterType((*GetListUserRequest)(nil), "user_service.GetListUserRequest")
	proto.RegisterType((*GetListUserResponse)(nil), "user_service.GetListUserResponse")
	proto.RegisterType((*UpdateUser)(nil), "user_service.UpdateUser")
	proto.RegisterType((*CheckUriRequest)(nil), "user_service.CheckUriRequest")
	proto.RegisterType((*CheckUriResponse)(nil), "user_service.CheckUriResponse")
	proto.RegisterType((*MessageString)(nil), "user_service.MessageString")
}

func init() {
	proto.RegisterFile("protos/auth/auth.proto", fileDescriptor_b6e5b8102c891c02)
}

var fileDescriptor_b6e5b8102c891c02 = []byte{
	// 630 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcb, 0x6e, 0x13, 0x31,
	0x14, 0xcd, 0x4c, 0x32, 0x69, 0xb8, 0x7d, 0x72, 0xa9, 0xca, 0x28, 0x40, 0x49, 0x0d, 0x42, 0x61,
	0x53, 0xa4, 0xb2, 0x61, 0xc3, 0x82, 0x3e, 0x54, 0xf5, 0x81, 0x54, 0xa6, 0x44, 0x42, 0xdd, 0x54,
	0x43, 0x72, 0x9b, 0x58, 0x69, 0xc6, 0xc1, 0x76, 0x40, 0x95, 0xd8, 0xf1, 0x07, 0xfc, 0x30, 0xc8,
	0xf6, 0x24, 0x1d, 0x27, 0xa4, 0xb0, 0x61, 0x13, 0xf9, 0x5c, 0x1f, 0x1f, 0x9f, 0xfb, 0x70, 0x06,
	0x36, 0x86, 0x52, 0x68, 0xa1, 0x5e, 0xa5, 0x23, 0xdd, 0xb3, 0x3f, 0xdb, 0x36, 0x80, 0x4b, 0x23,
	0x45, 0xf2, 0x52, 0x91, 0xfc, 0xca, 0xdb, 0xc4, 0x1a, 0xb0, 0xd2, 0x52, 0x24, 0xcf, 0x24, 0x1f,
	0xa4, 0xf2, 0xe6, 0x84, 0x6e, 0x70, 0x05, 0x42, 0xde, 0x89, 0x83, 0x46, 0xd0, 0x8c, 0x92, 0x90,
	0x77, 0xd8, 0x05, 0x54, 0x0c, 0x63, 0x3a, 0x8e, 0x08, 0x95, 0x2c, 0x1d, 0x50, 0x1c, 0x36, 0x82,
	0xe6, 0xbd, 0xc4, 0xae, 0x4d, 0x4c, 0x8a, 0x6b, 0x8a, 0xcb, 0x2e, 0x66, 0xd6, 0x58, 0x87, 0x9a,
	0xb9, 0xd1, 0x72, 0x2b, 0x36, 0x3e, 0xc1, 0xec, 0x67, 0x00, 0xb0, 0x27, 0x29, 0xd5, 0x64, 0xaf,
	0x18, 0x4b, 0x06, 0x05, 0xc9, 0xe2, 0xf1, 0xd0, 0x3f, 0x6e, 0xf6, 0x86, 0xa9, 0x52, 0xdf, 0x84,
	0xec, 0xe4, 0x57, 0x4e, 0xf0, 0xc4, 0x4a, 0xa5, 0x60, 0xe5, 0x39, 0x2c, 0x77, 0x29, 0x23, 0x99,
	0x6a, 0xfa, 0x28, 0xfa, 0x94, 0xc5, 0x51, 0x23, 0x68, 0xd6, 0x12, 0x3f, 0xc8, 0x8e, 0x61, 0xcd,
	0xb8, 0x39, 0x15, 0x5d, 0x9e, 0x25, 0xf4, 0x65, 0x44, 0x4a, 0x7b, 0x2e, 0x82, 0x3b, 0x5c, 0x84,
	0xbe, 0x0b, 0xf6, 0x23, 0x80, 0xfb, 0x05, 0x31, 0x35, 0x14, 0x99, 0x22, 0x7c, 0x01, 0x15, 0x73,
	0xda, 0x2a, 0x2d, 0xee, 0xe0, 0x76, 0xb1, 0x23, 0xdb, 0x86, 0x9e, 0xd8, 0x7d, 0xdc, 0x82, 0xa5,
	0xb4, 0xdd, 0x26, 0xa5, 0x2e, 0xb5, 0xb5, 0xeb, 0xd4, 0x17, 0x5d, 0xcc, 0x9a, 0xc5, 0x67, 0xb0,
	0x2c, 0xe9, 0x4a, 0x92, 0xea, 0xe5, 0x1c, 0x57, 0x87, 0xa5, 0x3c, 0xe8, 0x32, 0xfa, 0x04, 0x78,
	0x48, 0xfa, 0x94, 0x2b, 0x6d, 0xc5, 0xf3, 0x9c, 0xd6, 0x21, 0xba, 0xe6, 0x03, 0xae, 0xad, 0x8d,
	0x72, 0xe2, 0x00, 0x6e, 0x40, 0x55, 0x5c, 0x5d, 0x29, 0xd2, 0xf6, 0xb6, 0x72, 0x92, 0x23, 0xc3,
	0x16, 0xb2, 0x43, 0x32, 0xbf, 0xc0, 0x01, 0xd6, 0x82, 0x07, 0x9e, 0x72, 0x9e, 0xe0, 0x3a, 0x44,
	0x6d, 0x31, 0xca, 0x26, 0xd2, 0x16, 0x60, 0x13, 0x22, 0x93, 0x96, 0x8a, 0xc3, 0x46, 0x79, 0x4e,
	0xde, 0x8e, 0xc0, 0xbe, 0x03, 0xb4, 0x86, 0x9d, 0xf1, 0x58, 0xfc, 0x87, 0xc9, 0xf3, 0x9a, 0x16,
	0x4d, 0x35, 0xed, 0x03, 0xac, 0xee, 0xf5, 0xa8, 0xdd, 0x6f, 0x49, 0x5e, 0xa8, 0x95, 0x2b, 0xaf,
	0x6b, 0xbe, 0x03, 0xb8, 0x06, 0xe5, 0x91, 0xe4, 0xb9, 0x0f, 0xb3, 0x34, 0xd5, 0x1b, 0x90, 0xee,
	0x89, 0xf1, 0x3c, 0xe6, 0x88, 0xb5, 0x60, 0xed, 0x56, 0x32, 0x2f, 0xd2, 0x0a, 0x84, 0xa2, 0x6f,
	0x05, 0x6b, 0x49, 0x28, 0xfa, 0xf8, 0x10, 0x16, 0x6c, 0x41, 0xb8, 0x1b, 0xa3, 0x28, 0xa9, 0x1a,
	0x78, 0xd4, 0xc1, 0x18, 0x16, 0x06, 0xa4, 0x54, 0xda, 0x1d, 0xa7, 0x37, 0x86, 0xec, 0x25, 0x2c,
	0xbf, 0x77, 0xcb, 0x73, 0x2d, 0x79, 0xd6, 0x2d, 0x52, 0x03, 0x8f, 0xba, 0xf3, 0xab, 0x0c, 0x8b,
	0xef, 0x46, 0xba, 0x77, 0xee, 0xca, 0x8d, 0x27, 0x50, 0x1b, 0x3b, 0xc2, 0x27, 0x7e, 0x27, 0xa6,
	0x92, 0xaf, 0x6f, 0xce, 0xdb, 0x76, 0x89, 0xb0, 0x12, 0x1e, 0x40, 0xd5, 0x3d, 0x63, 0x8c, 0xa7,
	0xb8, 0x93, 0xc7, 0x5d, 0x7f, 0x3a, 0xdb, 0x6e, 0xef, 0x55, 0xb0, 0x12, 0x1e, 0x43, 0x64, 0x43,
	0xb8, 0x39, 0x97, 0xeb, 0x1c, 0xfd, 0x83, 0xd6, 0x5b, 0x58, 0x38, 0x24, 0xbd, 0x7b, 0x73, 0xb4,
	0x8f, 0x8f, 0x67, 0xd9, 0xb7, 0xff, 0x77, 0xf5, 0x3f, 0x8c, 0x21, 0x2b, 0xe1, 0x99, 0x3d, 0x6e,
	0x06, 0x1b, 0x1b, 0x3e, 0x61, 0xf6, 0x25, 0xd5, 0xb7, 0xee, 0x60, 0x4c, 0x0c, 0xbd, 0x81, 0xaa,
	0x9b, 0xe9, 0xe9, 0x1a, 0xdd, 0x4e, 0xfa, 0x1c, 0x2f, 0x07, 0x50, 0xdd, 0xa7, 0x6b, 0xd2, 0xf4,
	0x97, 0x4c, 0x1e, 0xf9, 0xbb, 0xde, 0x64, 0xb0, 0xd2, 0xee, 0xea, 0x85, 0xf9, 0xa3, 0xb3, 0x1f,
	0x01, 0xfb, 0x3d, 0xf8, 0x5c, 0xb5, 0xeb, 0xd7, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x05, 0x93,
	0x95, 0x65, 0x2a, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	CheckUri(ctx context.Context, in *CheckUriRequest, opts ...grpc.CallOption) (*CheckUriResponse, error)
	Create(ctx context.Context, in *CreateUser, opts ...grpc.CallOption) (*UserLoginResponse, error)
	Login(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginResponse, error)
	GetByID(ctx context.Context, in *UserPrimaryKey, opts ...grpc.CallOption) (*User, error)
	GetList(ctx context.Context, in *GetListUserRequest, opts ...grpc.CallOption) (*GetListUserResponse, error)
	Update(ctx context.Context, in *UpdateUser, opts ...grpc.CallOption) (*User, error)
	Delete(ctx context.Context, in *UserPrimaryKey, opts ...grpc.CallOption) (*MessageString, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) CheckUri(ctx context.Context, in *CheckUriRequest, opts ...grpc.CallOption) (*CheckUriResponse, error) {
	out := new(CheckUriResponse)
	err := c.cc.Invoke(ctx, "/user_service.AuthService/CheckUri", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Create(ctx context.Context, in *CreateUser, opts ...grpc.CallOption) (*UserLoginResponse, error) {
	out := new(UserLoginResponse)
	err := c.cc.Invoke(ctx, "/user_service.AuthService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginResponse, error) {
	out := new(UserLoginResponse)
	err := c.cc.Invoke(ctx, "/user_service.AuthService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetByID(ctx context.Context, in *UserPrimaryKey, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/user_service.AuthService/GetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetList(ctx context.Context, in *GetListUserRequest, opts ...grpc.CallOption) (*GetListUserResponse, error) {
	out := new(GetListUserResponse)
	err := c.cc.Invoke(ctx, "/user_service.AuthService/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Update(ctx context.Context, in *UpdateUser, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/user_service.AuthService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Delete(ctx context.Context, in *UserPrimaryKey, opts ...grpc.CallOption) (*MessageString, error) {
	out := new(MessageString)
	err := c.cc.Invoke(ctx, "/user_service.AuthService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	CheckUri(context.Context, *CheckUriRequest) (*CheckUriResponse, error)
	Create(context.Context, *CreateUser) (*UserLoginResponse, error)
	Login(context.Context, *UserLoginRequest) (*UserLoginResponse, error)
	GetByID(context.Context, *UserPrimaryKey) (*User, error)
	GetList(context.Context, *GetListUserRequest) (*GetListUserResponse, error)
	Update(context.Context, *UpdateUser) (*User, error)
	Delete(context.Context, *UserPrimaryKey) (*MessageString, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) CheckUri(ctx context.Context, req *CheckUriRequest) (*CheckUriResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUri not implemented")
}
func (*UnimplementedAuthServiceServer) Create(ctx context.Context, req *CreateUser) (*UserLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedAuthServiceServer) Login(ctx context.Context, req *UserLoginRequest) (*UserLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthServiceServer) GetByID(ctx context.Context, req *UserPrimaryKey) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (*UnimplementedAuthServiceServer) GetList(ctx context.Context, req *GetListUserRequest) (*GetListUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (*UnimplementedAuthServiceServer) Update(ctx context.Context, req *UpdateUser) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedAuthServiceServer) Delete(ctx context.Context, req *UserPrimaryKey) (*MessageString, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_CheckUri_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUriRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CheckUri(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_service.AuthService/CheckUri",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CheckUri(ctx, req.(*CheckUriRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_service.AuthService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Create(ctx, req.(*CreateUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_service.AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*UserLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_service.AuthService/GetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetByID(ctx, req.(*UserPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_service.AuthService/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetList(ctx, req.(*GetListUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_service.AuthService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Update(ctx, req.(*UpdateUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_service.AuthService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Delete(ctx, req.(*UserPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user_service.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckUri",
			Handler:    _AuthService_CheckUri_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _AuthService_Create_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _AuthService_GetByID_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _AuthService_GetList_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AuthService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AuthService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/auth/auth.proto",
}
